version: "3.8"
services:
  aiidalab:
    build: .
    ports:
      - ${AIIDALAB_PORT}:8888
    environment:
      - >
        AIIDALAB_DEFAULT_APPS=
        aiidalab-widgets-base
        quantum-espresso
      - JUPYTER_TOKEN
    volumes:
      - ~/aiidalab:/home/aiida
      - ~/orca:/opt/orca
