version: "3.8"
services:
  aiidalab-ispg:
    build: .
    ports:
      - ${AIIDALAB_PORT}:8888
    environment:
      - >
        AIIDALAB_DEFAULT_APPS=
        aiidalab-widgets-base
        # Uncomment this once the repo is public
        # git@github.com/danielhollas/aiidalab-ispg
      - JUPYTER_TOKEN
    volumes:
      - ${AIIDALAB_HOME}:/home/aiida
      - ${ORCA_HOME}:/opt/orca
